### PR TITLE
Fix link to projects in Portfolio Access Control view

### LINKED ISSUE #676: Malformed links to projects under Portfolio Access Control
### Current Behavior

In the Portfolio Access Control view, links to the corresponding projects are malformed which gives users 404 errors:
`https://dtrack.example.com/admin/projects/<uuid>`

The `admin` path causes the problem. 

### Steps to Reproduce

1. Enable the Portfolio Access Control feature
2. Under Portfolio Access Control, assign a project to a team 
3. Click on the project's name (link)

### Expected Behavior

Working link to the corresponding Dependency-Track project (without `admin` in the path)

### Dependency-Track Frontend Version

4.10.0

### Browser

Microsoft Edge

### Browser Version

120.0.2210.61

### Operating System

Windows

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/frontend/issues) for whether this defect was already reported

### PR DESCRIPTION
**Pull request by lukas-braune**
### Description

Fix link to projects in Portfolio Access Control view

### Addressed Issue

Fixes #676

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#pull-requests)
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

### CODE REVIEW

**Review by LaVibeX — CHANGES_REQUESTED** [review]
```suggestion
@@ -124,7 +124,10 @@ export default {
                 }
               },
               projectUri: function (uuid) {
-                const href = router.resolve({name: 'Project', params: {uuid: uuid}}).href;
+                const href = router.resolve({
+                  name: 'Project',
+                  params: { uuid: uuid },
+                }).href;
                 const sanitizedHref = xssFilters.uriInUnQuotedAttr(href);
                 return sanitizedHref;
               },
```

**Review by LaVibeX — APPROVED** [review]

File: src/views/administration/accessmanagement/PortfolioAccessControl.vue [hunk 1]
```diff
@@ -33,6 +33,7 @@ import permissionsMixin from '../../../mixins/permissionsMixin';
 import { Switch as cSwitch } from '@coreui/vue';
 import BInputGroupFormInput from '../../../forms/BInputGroupFormInput';
 import configPropertyMixin from '../mixins/configPropertyMixin';
+import router from '@/router'
```
Comment (LaVibeX) [inline src/views/administration/accessmanagement/PortfolioAccessControl.vue:36]:
```suggestion
import router from '@/router';
```

**Review by LaVibeX — CHANGES_REQUESTED** [review]
I forgot about that, just a simple ;

**Review by LaVibeX — APPROVED** [review]

**Review by nscuro — APPROVED** [review]
Thanks both!
